---
language: python
services: docker
cache: pip

env:
  global:
    - ROLE_NAME: mod_pagespeed
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME cloudweeb.$ROLE_NAME
  - cd cloudweeb.$ROLE_NAME

script:
  # Run tests.
  - molecule test
