---
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install OpenLiteSpeed
  include_tasks: 'install-{{ ansible_os_family }}.yml'
  tags: ['openlitespeed-install']

- name: Configure OpenLiteSpeed
  import_tasks: 'config.yml'

- name: Start and enable OpenLiteSpeed
  service:
    name: lsws
    state: started
    enabled: true
