---
- name: Include {{ ansible_os_family }} variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install OpenLiteSpeed
  include_tasks: 'install-{{ ansible_os_family }}.yml'
  tags: [ 'openlitespeed-install' ]

- name: Configure OpenLiteSpeed
  import_tasks: 'config.yml'

- name: Start and enable OpenLiteSpeed
  service:
    name: lsws
    state: started
    enabled: yes
